### ISSUE TITLE
We cannot import torch_musa

### ISSUE THREAD

**Issue by crafty11** [MooreThreads/torch_musa#24]
import torch
>>> import torch_musa
Traceback (most recent call last):
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch_musa-2.0.0-py3.8-linux-x86_64.egg/torch_musa/__init__.py", line 27, in <module>
    import torch_musa._MUSAC
ImportError: /usr/local/musa/lib/libmusa.so.1.0: undefined symbol: PVRSRVGetDevInfo

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch_musa-2.0.0-py3.8-linux-x86_64.egg/torch_musa/__init__.py", line 29, in <module>
    raise ImportError("Please try running Python from a different directory!") from err
ImportError: Please try running Python from a different directory!

**Comment by dixyes** [comment]
你得用最新的sdk。。。
这个仓库的轮子要用至少1.4.1rc的各种sdk版本

**Comment by crafty11** [comment]
我使用的docker安装的,我不知道你说的那个sdk是哪个，方便说一下吗，以及获取的方法

**Comment by dixyes** [comment]
> 我使用的docker安装的,我不知道你说的那个sdk是哪个，方便说一下吗，以及获取的方法

sdk: https://developer.mthreads.com/sdk/download/musa?equipment=&os=&driverVersion=&version=

如果使用的官方镜像，可以试试官方镜像的develop版本 或许有一个版本的镜像能和你的host的版本对的上，如果都对不上，也可以考虑换个host版本的container tool（上面url有多个版本）

**Comment by fmo-mt** [comment]
请参考最新README，安装MUSA SDK 4.2.0，更新torch_musa v2.1.0尝试，感谢
