### ISSUE TITLE
关于torch_musa环境配置及编译遇到的问题

### ISSUE THREAD

**Issue by 1012lq** [MooreThreads/torch_musa#34]
![20240318_121613](https://github.com/MooreThreads/torch_musa/assets/163710607/688f30c7-ccd1-4737-a822-8567e7aa926b)
以上是我验证torch_musa环境代码的运行结果
我的docker应该是安装成功了的，但是不知道如何使用
这是我的环境变量设置，存放在bashrc里，我不知道这样做是否正确

然后进入到推荐的脚本一键编译部分，首先需要cd torch_musa，但我找不到这个文件夹
所以我在网页里下载了一个带有torch_musa的文件夹，解压并进入以下文件夹试图尝试编译
下载的是这个
![20240318_121959](https://github.com/MooreThreads/torch_musa/assets/163710607/70827cd6-3ccd-4ef1-8ecb-3c5a80ec17f0)
接下来命令行输入bash build.sh会提示
![20240318_122017](https://github.com/MooreThreads/torch_musa/assets/163710607/97c0c9c4-9899-4e33-ab16-d3f2c4603815)
加上sudo bash build.sh报错消失 
然后出现报错build.sh: 行 131: python：未找到命令
我将图中标绿内容改为python3 setup.py clean，报错消失
![20240318_122108](https://github.com/MooreThreads/torch_musa/assets/163710607/2d612d00-4812-42ab-9d7a-efa151e7bc8b)

接下来输入sudo bash build.sh --torch
运行到最后会出现以下报错：（这个错误我无法解决，无法进一步编译了）
![Uploading 20240318_122234.png…]()

**Comment by 1012lq** [comment]
有两张图片上传失败了 补充一下
![20240318_121724](https://github.com/MooreThreads/torch_musa/assets/163710607/2a80479c-bfb1-4524-b3f9-00fffa8a8c0e)
![20240318_122234](https://github.com/MooreThreads/torch_musa/assets/163710607/b7624f80-4593-4568-8c72-88cee7915c91)

**Comment by hanhaowen-mt** [comment]
麻烦发一下您的docker启动命令，是v1.1.0分支README.md上的吗

**Comment by 1012lq** [comment]
> 麻烦发一下您的docker启动命令，是v1.1.0分支README.md上的吗 https://github.com/MooreThreads/torch_musa/tree/v1.1.0

运行的是这个

**Comment by 1012lq** [comment]
> 麻烦发一下您的docker启动命令，是v1.1.0分支README.md上的吗 https://github.com/MooreThreads/torch_musa/tree/v1.1.0

![Uploading Screenshot_20240318_140950_com.oray.sunlogin_edit_15839356986820.jpg…]()

**Comment by 1012lq** [comment]
> 麻烦发一下您的docker启动命令，是v1.1.0分支README.md上的吗 https://github.com/MooreThreads/torch_musa/tree/v1.1.0
好像无法看到图片  我把命令和报错复制过来了
(base) geohpc@geohpc-u1:~$ sudo docker run -it \
>     --privileged \
>     --name=torch_musa_release \
>     --env MTHREADS_VISIBLE_DEVICES=all \
>     registry.mthreads.com/mcconline/musa-pytorch-release-public:rc2.0.0-v1.1.0-S80-py38 \
>     /bin/bash
[sudo] geohpc 的密码： 
docker: Error response from daemon: Conflict. The container name "/torch_musa_release" is already in use by container "840b403c42525b76e9abe262ff9815e6d1a2c969d3b50ad3723b356d03dea7f0". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.

**Comment by hanhaowen-mt** [comment]
> > 麻烦发一下您的docker启动命令，是v1.1.0分支README.md上的吗 https://github.com/MooreThreads/torch_musa/tree/v1.1.0
> > 好像无法看到图片  我把命令和报错复制过来了
> > (base) geohpc@geohpc-u1:~$ sudo docker run -it 
> > --privileged 
> > --name=torch_musa_release 
> > --env MTHREADS_VISIBLE_DEVICES=all 
> > registry.mthreads.com/mcconline/musa-pytorch-release-public:rc2.0.0-v1.1.0-S80-py38 
> > /bin/bash
> > [sudo] geohpc 的密码：
> > docker: Error response from daemon: Conflict. The container name "/torch_musa_release" is already in use by container "840b403c42525b76e9abe262ff9815e6d1a2c969d3b50ad3723b356d03dea7f0". You have to remove (or rename) that container to be able to reuse that name.
> > See 'docker run --help'.

麻烦发一下完整的bash记录

**Comment by 1012lq** [comment]
> > > 麻烦发一下您的docker启动命令，是v1.1.0分支README.md上的吗 https://github.com/MooreThreads/torch_musa/tree/v1.1.0
> > > 好像无法看到图片  我把命令和报错复制过来了
> > > (base) geohpc@geohpc-u1:~$ sudo docker run -it
> > > --privileged
> > > --name=torch_musa_release
> > > --env MTHREADS_VISIBLE_DEVICES=all
> > > registry.mthreads.com/mcconline/musa-pytorch-release-public:rc2.0.0-v1.1.0-S80-py38
> > > /bin/bash
> > > [sudo] geohpc 的密码：
> > > docker: Error response from daemon: Conflict. The container name "/torch_musa_release" is already in use by container "840b403c42525b76e9abe262ff9815e6d1a2c969d3b50ad3723b356d03dea7f0". You have to remove (or rename) that container to be able to reuse that name.
> > > See 'docker run --help'.
> 
> 麻烦发一下完整的bash记录，从进入docker到出错的整个过程

没有记录了  可以告诉我怎么复现一下吗 或者怎样使正确的命令  我在尝试一下

**Comment by hanhaowen-mt** [comment]
> > > > 麻烦发一下您的docker启动命令，是v1.1.0分支README.md上的吗 https://github.com/MooreThreads/torch_musa/tree/v1.1.0
> > > > 好像无法看到图片  我把命令和报错复制过来了
> > > > (base) geohpc@geohpc-u1:~$ sudo docker run -it
> > > > --privileged
> > > > --name=torch_musa_release
> > > > --env MTHREADS_VISIBLE_DEVICES=all
> > > > registry.mthreads.com/mcconline/musa-pytorch-release-public:rc2.0.0-v1.1.0-S80-py38
> > > > /bin/bash
> > > > [sudo] geohpc 的密码：
> > > > docker: Error response from daemon: Conflict. The container name "/torch_musa_release" is already in use by container "840b403c42525b76e9abe262ff9815e6d1a2c969d3b50ad3723b356d03dea7f0". You have to remove (or rename) that container to be able to reuse that name.
> > > > See 'docker run --help'.
> > 
> > 
> > 麻烦发一下完整的bash记录，从进入docker到出错的整个过程
> 
> 没有记录了 可以告诉我怎么复现一下吗 或者怎样使正确的命令 我在尝试一下

#首先进入docker
docker run -it --privileged --pull always --network=host --name=torch_musa_dev --env MTHREADS_VISIBLE_DEVICES=all --shm-size=80g registry.mthreads.com/mcconline/musa-pytorch-dev-public:rc2.0.0-v1.1.0-S80-py38 /bin/bash

#然后安装
cd /home/torch_musa && bash build.sh

**Comment by 1012lq** [comment]
> > > > > 麻烦发一下您的docker启动命令，是v1.1.0分支README.md上的吗 https://github.com/MooreThreads/torch_musa/tree/v1.1.0
> > > > > 好像无法看到图片  我把命令和报错复制过来了
> > > > > (base) geohpc@geohpc-u1:~$ sudo docker run -it
> > > > > --privileged
> > > > > --name=torch_musa_release
> > > > > --env MTHREADS_VISIBLE_DEVICES=all
> > > > > registry.mthreads.com/mcconline/musa-pytorch-release-public:rc2.0.0-v1.1.0-S80-py38
> > > > > /bin/bash
> > > > > [sudo] geohpc 的密码：
> > > > > docker: Error response from daemon: Conflict. The container name "/torch_musa_release" is already in use by container "840b403c42525b76e9abe262ff9815e6d1a2c969d3b50ad3723b356d03dea7f0". You have to remove (or rename) that container to be able to reuse that name.
> > > > > See 'docker run --help'.
> > > 
> > > 
> > > 麻烦发一下完整的bash记录，从进入docker到出错的整个过程
> > 
> > 
> > 没有记录了 可以告诉我怎么复现一下吗 或者怎样使正确的命令 我在尝试一下
> 
> #首先进入docker docker run -it --privileged --pull always --network=host --name=torch_musa_dev --env MTHREADS_VISIBLE_DEVICES=all --shm-size=80g registry.mthreads.com/mcconline/musa-pytorch-dev-public:rc2.0.0-v1.1.0-S80-py38 /bin/bash
> 
> #然后安装 cd /home/torch_musa && bash build.sh

之前是我进入docker的命令输入的不正确，现在成功进去docker且完成命令bash build.sh运行 （期间有好几个cmake error，我随机翻译了一个，说是针对项目开发人员的，那么对我来说是可以忽略的对吧），现在我应该继续运行 bash build.sh --torch命令对吗

**Comment by hanhaowen-mt** [comment]
> > > > > > 麻烦发一下您的docker启动命令，是v1.1.0分支README.md上的吗 https://github.com/MooreThreads/torch_musa/tree/v1.1.0
> > > > > > 好像无法看到图片  我把命令和报错复制过来了
> > > > > > (base) geohpc@geohpc-u1:~$ sudo docker run -it
> > > > > > --privileged
> > > > > > --name=torch_musa_release
> > > > > > --env MTHREADS_VISIBLE_DEVICES=all
> > > > > > registry.mthreads.com/mcconline/musa-pytorch-release-public:rc2.0.0-v1.1.0-S80-py38
> > > > > > /bin/bash
> > > > > > [sudo] geohpc 的密码：
> > > > > > docker: Error response from daemon: Conflict. The container name "/torch_musa_release" is already in use by container "840b403c42525b76e9abe262ff9815e6d1a2c969d3b50ad3723b356d03dea7f0". You have to remove (or rename) that container to be able to reuse that name.
> > > > > > See 'docker run --help'.
> > > > 
> > > > 
> > > > 麻烦发一下完整的bash记录，从进入docker到出错的整个过程
> > > 
> > > 
> > > 没有记录了 可以告诉我怎么复现一下吗 或者怎样使正确的命令 我在尝试一下
> > 
> > 
> > #首先进入docker docker run -it --privileged --pull always --network=host --name=torch_musa_dev --env MTHREADS_VISIBLE_DEVICES=all --shm-size=80g registry.mthreads.com/mcconline/musa-pytorch-dev-public:rc2.0.0-v1.1.0-S80-py38 /bin/bash
> > #然后安装 cd /home/torch_musa && bash build.sh
> 
> 之前是我进入docker的命令输入的不正确，现在成功进去docker且完成命令bash build.sh运行 （期间有好几个cmake error，我随机翻译了一个，说是针对项目开发人员的，那么对我来说是可以忽略的对吧），现在我应该继续运行 bash build.sh --torch命令对吗

是的，可以忽略，bash build.sh --torch只编译并安装了CPU版本的pytorch，如果想用上torch_musa，则可以bash build.sh来同时安装pytorch和torch_musa，如果修改了pytorch/torch_musa的源码并且想再次安装，就bash build.sh -c

**Comment by caizhi-mt** [comment]
torch_musa刚更新过代码，建议使用新的驱动和新的torch_musa开发镜像去编译torch_musa。
1. 驱动下载地址：

**Comment by 1012lq** [comment]
> torch_musa刚更新过代码，建议使用新的驱动和新的torch_musa开发镜像去编译torch_musa。
> 
> 1. 驱动下载地址：
下载链接没有显示出来，那我应该从哪一步重新开始

**Comment by 1012lq** [comment]
> > > > > > > 麻烦发一下您的docker启动命令，是v1.1.0分支README.md上的吗 https://github.com/MooreThreads/torch_musa/tree/v1.1.0
> > > > > > > 好像无法看到图片  我把命令和报错复制过来了
> > > > > > > (base) geohpc@geohpc-u1:~$ sudo docker run -it
> > > > > > > --privileged
> > > > > > > --name=torch_musa_release
> > > > > > > --env MTHREADS_VISIBLE_DEVICES=all
> > > > > > > registry.mthreads.com/mcconline/musa-pytorch-release-public:rc2.0.0-v1.1.0-S80-py38
> > > > > > > /bin/bash
> > > > > > > [sudo] geohpc 的密码：
> > > > > > > docker: Error response from daemon: Conflict. The container name "/torch_musa_release" is already in use by container "840b403c42525b76e9abe262ff9815e6d1a2c969d3b50ad3723b356d03dea7f0". You have to remove (or rename) that container to be able to reuse that name.
> > > > > > > See 'docker run --help'.
> > > > > 
> > > > > 
> > > > > 麻烦发一下完整的bash记录，从进入docker到出错的整个过程
> > > > 
> > > > 
> > > > 没有记录了 可以告诉我怎么复现一下吗 或者怎样使正确的命令 我在尝试一下
> > > 
> > > 
> > > #首先进入docker docker run -it --privileged --pull always --network=host --name=torch_musa_dev --env MTHREADS_VISIBLE_DEVICES=all --shm-size=80g registry.mthreads.com/mcconline/musa-pytorch-dev-public:rc2.0.0-v1.1.0-S80-py38 /bin/bash
> > > #然后安装 cd /home/torch_musa && bash build.sh
> > 
> > 
> > 之前是我进入docker的命令输入的不正确，现在成功进去docker且完成命令bash build.sh运行 （期间有好几个cmake error，我随机翻译了一个，说是针对项目开发人员的，那么对我来说是可以忽略的对吧），现在我应该继续运行 bash build.sh --torch命令对吗
> 
> 是的，可以忽略，bash build.sh --torch只编译并安装了CPU版本的pytorch，如果想用上torch_musa，则可以bash build.sh来同时安装pytorch和torch_musa，如果修改了pytorch/torch_musa的源码并且想再次安装，就bash build.sh -c

我的电脑在输入命令时卡掉了，如果重启的话，是不是要从进入docker这一步重新开始，那么还要进行什么删除操作吗

**Comment by hanhaowen-mt** [comment]
> > > > > > > > 麻烦发一下您的docker启动命令，是v1.1.0分支README.md上的吗 https://github.com/MooreThreads/torch_musa/tree/v1.1.0
> > > > > > > > 好像无法看到图片  我把命令和报错复制过来了
> > > > > > > > (base) geohpc@geohpc-u1:~$ sudo docker run -it
> > > > > > > > --privileged
> > > > > > > > --name=torch_musa_release
> > > > > > > > --env MTHREADS_VISIBLE_DEVICES=all
> > > > > > > > registry.mthreads.com/mcconline/musa-pytorch-release-public:rc2.0.0-v1.1.0-S80-py38
> > > > > > > > /bin/bash
> > > > > > > > [sudo] geohpc 的密码：
> > > > > > > > docker: Error response from daemon: Conflict. The container name "/torch_musa_release" is already in use by container "840b403c42525b76e9abe262ff9815e6d1a2c969d3b50ad3723b356d03dea7f0". You have to remove (or rename) that container to be able to reuse that name.
> > > > > > > > See 'docker run --help'.
> > > > > > 
> > > > > > 
> > > > > > 麻烦发一下完整的bash记录，从进入docker到出错的整个过程
> > > > > 
> > > > > 
> > > > > 没有记录了 可以告诉我怎么复现一下吗 或者怎样使正确的命令 我在尝试一下
> > > > 
> > > > 
> > > > #首先进入docker docker run -it --privileged --pull always --network=host --name=torch_musa_dev --env MTHREADS_VISIBLE_DEVICES=all --shm-size=80g registry.mthreads.com/mcconline/musa-pytorch-dev-public:rc2.0.0-v1.1.0-S80-py38 /bin/bash
> > > > #然后安装 cd /home/torch_musa && bash build.sh
> > > 
> > > 
> > > 之前是我进入docker的命令输入的不正确，现在成功进去docker且完成命令bash build.sh运行 （期间有好几个cmake error，我随机翻译了一个，说是针对项目开发人员的，那么对我来说是可以忽略的对吧），现在我应该继续运行 bash build.sh --torch命令对吗
> > 
> > 
> > 是的，可以忽略，bash build.sh --torch只编译并安装了CPU版本的pytorch，如果想用上torch_musa，则可以bash build.sh来同时安装pytorch和torch_musa，如果修改了pytorch/torch_musa的源码并且想再次安装，就bash build.sh -c
> 
> 我的电脑在输入命令时卡掉了，如果重启的话，是不是要从进入docker这一步重新开始，那么还要进行什么删除操作吗

docker start xxx && docker exec -ti xxx /bin/bash即可，更详细的可以上网搜docker学习教程。

**Comment by 1012lq** [comment]
> > > > > > > 麻烦发一下您的docker启动命令，是v1.1.0分支README.md上的吗 https://github.com/MooreThreads/torch_musa/tree/v1.1.0
> > > > > > > 好像无法看到图片  我把命令和报错复制过来了
> > > > > > > (base) geohpc@geohpc-u1:~$ sudo docker run -it
> > > > > > > --privileged
> > > > > > > --name=torch_musa_release
> > > > > > > --env MTHREADS_VISIBLE_DEVICES=all
> > > > > > > registry.mthreads.com/mcconline/musa-pytorch-release-public:rc2.0.0-v1.1.0-S80-py38
> > > > > > > /bin/bash
> > > > > > > [sudo] geohpc 的密码：
> > > > > > > docker: Error response from daemon: Conflict. The container name "/torch_musa_release" is already in use by container "840b403c42525b76e9abe262ff9815e6d1a2c969d3b50ad3723b356d03dea7f0". You have to remove (or rename) that container to be able to reuse that name.
> > > > > > > See 'docker run --help'.
> > > > > 
> > > > > 
> > > > > 麻烦发一下完整的bash记录，从进入docker到出错的整个过程
> > > > 
> > > > 
> > > > 没有记录了 可以告诉我怎么复现一下吗 或者怎样使正确的命令 我在尝试一下
> > > 
> > > 
> > > #首先进入docker docker run -it --privileged --pull always --network=host --name=torch_musa_dev --env MTHREADS_VISIBLE_DEVICES=all --shm-size=80g registry.mthreads.com/mcconline/musa-pytorch-dev-public:rc2.0.0-v1.1.0-S80-py38 /bin/bash
> > > #然后安装 cd /home/torch_musa && bash build.sh
> > 
> > 
> > 之前是我进入docker的命令输入的不正确，现在成功进去docker且完成命令bash build.sh运行 （期间有好几个cmake error，我随机翻译了一个，说是针对项目开发人员的，那么对我来说是可以忽略的对吧），现在我应该继续运行 bash build.sh --torch命令对吗
> 
> 是的，可以忽略，bash build.sh --torch只编译并安装了CPU版本的pytorch，如果想用上torch_musa，则可以bash build.sh来同时安装pytorch和torch_musa，如果修改了pytorch/torch_musa的源码并且想再次安装，就bash build.sh -c

运行bash build.sh --pytorch命令或者bash build.sh --torch_musa 会提示 unrecognized option "--pytorch"

**Comment by hanhaowen-mt** [comment]
> > > > > > > > 麻烦发一下您的docker启动命令，是v1.1.0分支README.md上的吗 https://github.com/MooreThreads/torch_musa/tree/v1.1.0
> > > > > > > > 好像无法看到图片  我把命令和报错复制过来了
> > > > > > > > (base) geohpc@geohpc-u1:~$ sudo docker run -it
> > > > > > > > --privileged
> > > > > > > > --name=torch_musa_release
> > > > > > > > --env MTHREADS_VISIBLE_DEVICES=all
> > > > > > > > registry.mthreads.com/mcconline/musa-pytorch-release-public:rc2.0.0-v1.1.0-S80-py38
> > > > > > > > /bin/bash
> > > > > > > > [sudo] geohpc 的密码：
> > > > > > > > docker: Error response from daemon: Conflict. The container name "/torch_musa_release" is already in use by container "840b403c42525b76e9abe262ff9815e6d1a2c969d3b50ad3723b356d03dea7f0". You have to remove (or rename) that container to be able to reuse that name.
> > > > > > > > See 'docker run --help'.
> > > > > > 
> > > > > > 
> > > > > > 麻烦发一下完整的bash记录，从进入docker到出错的整个过程
> > > > > 
> > > > > 
> > > > > 没有记录了 可以告诉我怎么复现一下吗 或者怎样使正确的命令 我在尝试一下
> > > > 
> > > > 
> > > > #首先进入docker docker run -it --privileged --pull always --network=host --name=torch_musa_dev --env MTHREADS_VISIBLE_DEVICES=all --shm-size=80g registry.mthreads.com/mcconline/musa-pytorch-dev-public:rc2.0.0-v1.1.0-S80-py38 /bin/bash
> > > > #然后安装 cd /home/torch_musa && bash build.sh
> > > 
> > > 
> > > 之前是我进入docker的命令输入的不正确，现在成功进去docker且完成命令bash build.sh运行 （期间有好几个cmake error，我随机翻译了一个，说是针对项目开发人员的，那么对我来说是可以忽略的对吧），现在我应该继续运行 bash build.sh --torch命令对吗
> > 
> > 
> > 是的，可以忽略，bash build.sh --torch只编译并安装了CPU版本的pytorch，如果想用上torch_musa，则可以bash build.sh来同时安装pytorch和torch_musa，如果修改了pytorch/torch_musa的源码并且想再次安装，就bash build.sh -c
> 
> 运行bash build.sh --pytorch命令或者bash build.sh --torch_musa 会提示 unrecognized option "--pytorch"

bash build.sh --torch而非bash build.sh --pytorch

**Comment by 1012lq** [comment]
> > > > > > > > > 麻烦发一下您的docker启动命令，是v1.1.0分支README.md上的吗 https://github.com/MooreThreads/torch_musa/tree/v1.1.0
> > > > > > > > > 好像无法看到图片  我把命令和报错复制过来了
> > > > > > > > > (base) geohpc@geohpc-u1:~$ sudo docker run -it
> > > > > > > > > --privileged
> > > > > > > > > --name=torch_musa_release
> > > > > > > > > --env MTHREADS_VISIBLE_DEVICES=all
> > > > > > > > > registry.mthreads.com/mcconline/musa-pytorch-release-public:rc2.0.0-v1.1.0-S80-py38
> > > > > > > > > /bin/bash
> > > > > > > > > [sudo] geohpc 的密码：
> > > > > > > > > docker: Error response from daemon: Conflict. The container name "/torch_musa_release" is already in use by container "840b403c42525b76e9abe262ff9815e6d1a2c969d3b50ad3723b356d03dea7f0". You have to remove (or rename) that container to be able to reuse that name.
> > > > > > > > > See 'docker run --help'.
> > > > > > > 
> > > > > > > 
> > > > > > > 麻烦发一下完整的bash记录，从进入docker到出错的整个过程
> > > > > > 
> > > > > > 
> > > > > > 没有记录了 可以告诉我怎么复现一下吗 或者怎样使正确的命令 我在尝试一下
> > > > > 
> > > > > 
> > > > > #首先进入docker docker run -it --privileged --pull always --network=host --name=torch_musa_dev --env MTHREADS_VISIBLE_DEVICES=all --shm-size=80g registry.mthreads.com/mcconline/musa-pytorch-dev-public:rc2.0.0-v1.1.0-S80-py38 /bin/bash
> > > > > #然后安装 cd /home/torch_musa && bash build.sh
> > > > 
> > > > 
> > > > 之前是我进入docker的命令输入的不正确，现在成功进去docker且完成命令bash build.sh运行 （期间有好几个cmake error，我随机翻译了一个，说是针对项目开发人员的，那么对我来说是可以忽略的对吧），现在我应该继续运行 bash build.sh --torch命令对吗
> > > 
> > > 
> > > 是的，可以忽略，bash build.sh --torch只编译并安装了CPU版本的pytorch，如果想用上torch_musa，则可以bash build.sh来同时安装pytorch和torch_musa，如果修改了pytorch/torch_musa的源码并且想再次安装，就bash build.sh -c
> > 
> > 
> > 运行bash build.sh --pytorch命令或者bash build.sh --torch_musa 会提示 unrecognized option "--pytorch"
> 
> bash build.sh --torch而非bash build.sh --pytorch bash build.sh --musa而非bash build.sh --torch_musa

当我运行完bash build.sh   # build original only. and torch_musa from scratch

# Some important parameters are as follows:
bash build.sh --torch  # build original PyTorch only
bash build.sh --musa   # build torch_musa only
bash build.sh --fp64   # compile fp64 in kernels using mcc in torch_musa
bash build.sh --debug  # build in debug mode
bash build.sh --asan   # build in asan mode.Traceback (most recent call last):
  File "/home/geohpc/anaconda3/envs/DeepLearning/lib/python3.8/site-packages/torch_musa/__init__.py", line 34, in <module>
    import torch_musa._MUSAC
ImportError: libmudnn.so.2: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/geohpc/lqqq/pythonProject/test.py", line 2, in <module>
    import torch_musa
  File "/home/geohpc/anaconda3/envs/DeepLearning/lib/python3.8/site-packages/torch_musa/__init__.py", line 36, in <module>
    raise ImportError("Please try running Python from a different directory!") from err
ImportError: Please try running Python from a different directory!     然后我运行的我的深度学习的代码提示
bash build.sh --clean  # clean everything built and build.这些代码后 我测试torch_musa环境的代码还是提示    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled.    哪里出了问题呢

**Comment by 1012lq** [comment]
> @1012lq 麻烦给出具体的、完整的bash操作记录以及报错记录，从而方便我们复现问题。

bash build.sh   -c
bash build.sh --torch  
bash build.sh --musa   
bash build.sh --fp64   
bash build.sh --debug 
bash build.sh --asan   
bash build.sh --clean
![Screenshot_20240318_185617_com oray sunlogin](https://github.com/MooreThreads/torch_musa/assets/163710607/d675c861-6693-4c5a-9f5c-3e027b33a8ec)
但是运行时出现的东西很长 这要怎么提供

**Comment by caizhi-mt** [comment]
https://github.com/MooreThreads/torch_musa/blob/main/docs/MooreThreads-Torch_MUSA-Developer-Guide-CN-v1.1.0.pdf

**Comment by caizhi-mt** [comment]
新的开发者容器，执行下述命令`cd /home/torch_musa; bash build.sh -c`，看看是否有报错？

**Comment by 1012lq** [comment]
> @1012lq 麻烦给出具体的、完整的bash操作记录以及报错记录，从而方便我们

> 新的开发者容器，执行下述命令`cd /home/torch_musa; bash build.sh -c`，看看是否有报错？

![Image_1710761062104](https://github.com/MooreThreads/torch_musa/assets/163710607/27e73a6d-d2a8-4c2f-be28-f71414e48da9)
![Image_1710761062186](https://github.com/MooreThreads/torch_musa/assets/163710607/02ab7344-77b5-4df7-9173-1b388b776c0a)
![Image_1710761062222](https://github.com/MooreThreads/torch_musa/assets/163710607/a026ed21-bbcc-49a3-b764-ea4bbbbecf96)
![Image_1710761062299](https://github.com/MooreThreads/torch_musa/assets/163710607/517cec22-1df8-49f9-8e05-a1dcb17b9dba)
![Image_1710761062360](https://github.com/MooreThreads/torch_musa/assets/163710607/c76bd4cf-4c2a-4992-a15c-625ec0aa1bcc)
![Image_1710761062400](https://github.com/MooreThreads/torch_musa/assets/163710607/635ba8c1-b7cb-4401-8ee7-4c14b52295fa)
![Image_1710761062424](https://github.com/MooreThreads/torch_musa/assets/163710607/4df8b7c1-3a27-4e8f-aab9-4981f5047266)
![Image_1710761062470](https://github.com/MooreThreads/torch_musa/assets/163710607/09ca9d5d-7287-4ee3-852b-341e92319505)
![Image_1710761062477](https://github.com/MooreThreads/torch_musa/assets/163710607/018e1170-e4f1-473e-b265-58009e95cd67)
![Image_1710761062513](https://github.com/MooreThreads/torch_musa/assets/163710607/f2a32276-c3e7-478d-a0fd-0d62261d43fb)
![Image_1710761062539](https://github.com/MooreThreads/torch_musa/assets/163710607/56700ea9-8b79-4cce-bb60-a190e8eca775)
![Image_1710761196110](https://github.com/MooreThreads/torch_musa/assets/163710607/b70d2ace-f798-47f8-b659-fc2707fa57fe)
![Image_1710761191559](https://github.com/MooreThreads/torch_musa/assets/163710607/be79bc65-fa2f-44c1-8128-5825fb916844)
还没运行完 先提供这些 有新的我再补充

**Comment by caizhi-mt** [comment]
> > @1012lq 麻烦给出具体的、完整的bash操作记录以及报错记录，从而方便我们复现问题。
> 
> bash build.sh -c bash build.sh --torch bash build.sh --musa bash build.sh --fp64 bash build.sh --debug bash build.sh --asan bash build.sh --clean ![Screenshot_20240318_185617_com oray sunlogin](https://private-user-images.githubusercontent.com/163710607/313647338-d675c861-6693-4c5a-9f5c-3e027b33a8ec.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NjEzMDMsIm5iZiI6MTcxMDc2MTAwMywicGF0aCI6Ii8xNjM3MTA2MDcvMzEzNjQ3MzM4LWQ2NzVjODYxLTY2OTMtNGM1YS05ZjVjLTNlMDI3YjMzYThlYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQxMTIzMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MzNmODdkMTUyZjhkYzRjMDdlMTcwZjY1NzM5ODVlZDQ1ZjM2ZDFjMjExYTZmZjg3YTE1NTM0N2UyYzM4Y2VmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lkyR-9u-hxe4ocfuaODDNORG9g_pVaM5Gdzs8mzY70g) 但是运行时出现的东西很长 这要怎么提供

提供你在terminal中依次敲了哪些命令，以及哪里报错了？不用贴所有的log
