### ISSUE TITLE
torchaudio使用报错，似乎需要适配？

### ISSUE THREAD

**Issue by KakaruHayate** [MooreThreads/torch_musa#40]
```
Traceback (most recent call last):
  File "/home/kakaru/DDSP-SVC-MUSA/train_diff.py", line 8, in <module>
    from diffusion.vocoder import Vocoder, Unit2Mel, Unit2Wav, Unit2WavFast
  File "/home/kakaru/DDSP-SVC-MUSA/diffusion/vocoder.py", line 10, in <module>
    from torchaudio.transforms import Resample
  File "/home/kakaru/anaconda3/envs/gptsovits/lib/python3.9/site-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "/home/kakaru/anaconda3/envs/gptsovits/lib/python3.9/site-packages/torchaudio/_extension/__init__.py", line 43, in <module>
    _load_lib("libtorchaudio")
  File "/home/kakaru/anaconda3/envs/gptsovits/lib/python3.9/site-packages/torchaudio/_extension/utils.py", line 61, in _load_lib
    torch.ops.load_library(path)
  File "/home/kakaru/anaconda3/envs/gptsovits/lib/python3.9/site-packages/torch/_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "/home/kakaru/anaconda3/envs/gptsovits/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtorch_cuda.so: cannot open shared object file: No such file or directory
```

安装了torch2.0.0对应的torchaudio2.0.1后，仍然在读取cuda相关的动态库

```
Traceback (most recent call last):
  File "/home/kakaru/DDSP-SVC-MUSA/train_diff.py", line 8, in <module>
    from diffusion.vocoder import Vocoder, Unit2Mel, Unit2Wav, Unit2WavFast
  File "/home/kakaru/DDSP-SVC-MUSA/diffusion/vocoder.py", line 10, in <module>
    from torchaudio.transforms import Resample
  File "/home/kakaru/anaconda3/envs/gptsovits/lib/python3.9/site-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "/home/kakaru/anaconda3/envs/gptsovits/lib/python3.9/site-packages/torchaudio/_extension/__init__.py", line 43, in <module>
    _load_lib("libtorchaudio")
  File "/home/kakaru/anaconda3/envs/gptsovits/lib/python3.9/site-packages/torchaudio/_extension/utils.py", line 61, in _load_lib
    torch.ops.load_library(path)
  File "/home/kakaru/anaconda3/envs/gptsovits/lib/python3.9/site-packages/torch/_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "/home/kakaru/anaconda3/envs/gptsovits/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/kakaru/anaconda3/envs/gptsovits/lib/python3.9/site-packages/torchaudio/lib/libtorchaudio.so: undefined symbol: _ZNK5torch8autograd4Node4nameEv
```

而安装cpu版本的torchaudio后，以上的符号提示未定义

这个库对于语音合成方向还是很重要的

**Comment by hanhaowen-mt** [comment]
先安装好torch torch_musa，然后USE_CUDA=0 python setup.py install来安装torchaudio

**Comment by KakaruHayate** [comment]
> 先安装好torch torch_musa，然后USE_CUDA=0 python setup.py install来安装torchaudio

从source安装有点麻烦了，还是希望有wheel):

**Comment by hanhaowen-mt** [comment]
> > 先安装好torch torch_musa，然后USE_CUDA=0 python setup.py install来安装torchaudio
> 
> 从source安装有点麻烦了，还是希望有wheel):

直接安装cpu版本的torchaudio whl包应该没问题

**Comment by KakaruHayate** [comment]
> > > 先安装好torch torch_musa，然后USE_CUDA=0 python setup.py install来安装torchaudio
> > 
> > 
> > 从source安装有点麻烦了，还是希望有wheel):
> 
> 直接安装cpu版本的torchaudio whl包应该没问题

undefined symbol: _ZNK5torch8autograd4Node4nameEv

试了很多版本都是不行的，看来只能source安装了

**Comment by hanhaowen-mt** [comment]
可以用registry.mthreads.com/mcconline/musa-pytorch-dev-public:rc2.0.0-v1.1.0-S80-py38，dev版本的docker是安装了torchaudio的，不过是CPU版本的

**Comment by hanhaowen-mt** [comment]
可以用dev版本的docker registry.mthreads.com/mcconline/musa-pytorch-dev-public:rc2.0.0-v1.1.0-S80-py38，里面有cpu版本的torchaudio @KakaruHayate

**Comment by mingyuanw-mt** [comment]
> > > > 先安装好torch torch_musa，然后USE_CUDA=0 python setup.py install来安装torchaudio
> > > 
> > > 
> > > 从source安装有点麻烦了，还是希望有wheel):
> > 
> > 
> > 直接安装cpu版本的torchaudio whl包应该没问题
> 
> undefined symbol: _ZNK5torch8autograd4Node4nameEv
> 
> 试了很多版本都是不行的，看来只能source安装了

pytorch相关的wheel packages均在`cxx11_abi=0`模式下构建（pytorch貌似目前仍然未提供`cxx11_abi=1`构建好的包https://github.com/pytorch/pytorch/issues/51039 ）  
  
我们提供的pytorch wheel包基于`cxx11_abi=1`构建，因此会出现符号未定义错误。可尝试 @hanhaowen-mt 提供的方法，在docker里通过源码编译出torchaudio的whl包

**Comment by KakaruHayate** [comment]
> > > > > 先安装好torch torch_musa，然后USE_CUDA=0 python setup.py install来安装torchaudio
> > > > 
> > > > 
> > > > 从source安装有点麻烦了，还是希望有wheel):
> > > 
> > > 
> > > 直接安装cpu版本的torchaudio whl包应该没问题
> > 
> > 
> > undefined symbol: _ZNK5torch8autograd4Node4nameEv
> > 试了很多版本都是不行的，看来只能source安装了
> 
> pytorch相关的wheel packages均在`cxx11_abi=0`模式下构建（pytorch貌似目前仍然未提供`cxx11_abi=1`构建好的包[pytorch/pytorch#51039](https://github.com/pytorch/pytorch/issues/51039) ）
> 
> 我们提供的pytorch wheel包基于`cxx11_abi=1`构建，因此会出现符号未定义错误。可尝试 @hanhaowen-mt 提供的方法，在docker里通过源码编译出torchaudio的whl包

感谢回复，不过我没有docker测试条件

通过source安装已经解决我的问题了，先close了
