### ISSUE TITLE
Error when mapping the model to device "musa"

### ISSUE THREAD

**Issue by Ramseyous0109** [MooreThreads/torch_musa#44]
Error occurred when running the training demo in [README.md](https://github.com/MooreThreads/torch_musa/blob/main/README.md): 
```
Traceback (most recent call last):
  File "/home/mt/buaa/try_musa/classification/train_written_network.py", line 50, in <module>
    net = Net().to(device)
  File "/home/mt/buaa/anaconda3/envs/try_musa/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/home/mt/buaa/anaconda3/envs/try_musa/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/mt/buaa/anaconda3/envs/try_musa/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/home/mt/buaa/anaconda3/envs/try_musa/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/home/mt/buaa/anaconda3/envs/try_musa/lib/python3.10/site-packages/torch_musa/core/tensor_attrs.py", line 35, in _to
    return self.orig_to(*args, **kwargs)
RuntimeError: MUSA error: no CUDA-capable device is detected
```

The installation of MUSA and torch-musa is successful, versions listed: 

- System: Ubuntu 20.04
- GPU: S80
- MUSA-SDK: rc2.0.0
- MUSA_Toolkit: rc2.0.0
- muDNN: rc2.4.0
- torch_musa-1.1.0-cp310

**Comment by hanhaowen-mt** [comment]
目测是驱动没装好，可以使用docker试试，用developer版本的docker
