### ISSUE TITLE
导入torch和torch_musa报错libmupti.so.0.2文件找不到

### ISSUE THREAD

**Issue by SChaoZh** [MooreThreads/torch_musa#56]
按照教程安装完驱动，MUSA_Toolkits_rc2.0.0，muDNN后安装完S3000_S80_torch_musa-1.2.1-cp39-cp39-linux_x86_64.whl，torch-2.0.0-cp39-cp39-linux_x86_64.whl，torchaudio-2.0.1+3b40834-cp39-cp39-linux_x86_64.whl，torchvision-0.15.2a0+fa99a53-cp39-cp39-linux_x86_64.whl后，在ipynb文件中import torch和 import torch_musa均报错：libmupti.so.0.2: cannot open shared object file: No such file or directory"

我的musa_toolkits为
musa_toolkits:
{
	"version":	"2.0.0",
	"git branch":	"rc2.1.0",
	"git tag":	"No tag",
	"commit id":	"167f0f431ef649261f1310ee44002c14229c4bf2",
	"commit date":	"2024-03-27 10:20:48 +0800"
}
mcc:
{
	"version":	"2.1.0",
	"git branch":	"rc2.1.0",
	"git tag":	"No tag",
	"commit id":	"d4847756f2c727647d3956a6a7713ce1ef175967",
	"commit date":	"2024-03-22 14:56:38 +0800"
}
muAlg_dev:
{
	"version":	"0.3.0",
	"git branch":	"HEAD",
	"commit id":	"c6cf2b330bd7ff59ea5f9ae1444efdb0d117deb5",
	"commit date":	"2024-03-12 11:32:20 +0800"
}
mublas:
{
	"version":	"1.4.0",
	"build archs":	"21",
	"git branch":	"rc1.4.0",
	"git tag":	"20240326_develop",
	"commit id":	"685a379fcbd82a380b648c66f789394c4c988dec",
	"commit date":	"2024-03-26 17:12:48 +0800"
}
mufft:
{
	"version":	"1.4.0",
	"build archs":	"21",
	"git branch":	"rc1.4.0",
	"git tag":	"No tag",
	"commit id":	"9dc0357cc52b26c6b97db2efeda59739471c57b5",
	"commit date":	"2024-03-25 17:35:49 +0800"
}
muPP:
{
	"version":	"1.5.0",
	"build archs":	"21",
	"git branch":	"dev1.5.0",
	"git tag":	"No tag",
	"commit id":	"ab0e93f34d071e592dac1a27f4f3f67498206b6a",
	"commit date":	"2024-03-22 16:46:40 +0800"
}
murand:
{
	"version":	"1.0.0",
	"build archs":	"21",
	"git branch":	"rtm1.0.1",
	"git tag":	"No tag",
	"commit id":	"7d51b970329c0221b22abca45e230f772d0a6ed8",
	"commit date":	"2024-03-26 17:45:41 +0800"
}
musify:
{
	"version":	"0.2.0",
	"git branch":	"master",
	"commit id":	"fd863b384f528f0e7d9a29856029e68e20130489",
	"commit date":	"2024-03-12 15:52:53 +0800"
}
musparse:
{
	"version":	"0.4.0",
	"build archs":	"21",
	"git branch":	"HEAD",
	"git tag":	"20240326_develop",
	"commit id":	"382eae4a5be29c732a0d8b86069c2c63b3919459",
	"commit date":	"2024-03-26 17:23:09 +0800"
}
muThrust_dev:
{
	"version":	"0.3.0",
	"git branch":	"HEAD",
	"commit id":	"1b4d389f282c589754c7ee3b4d8077d220898f5b",
	"commit date":	"2024-03-12 11:51:38 +0800"
}
musa_runtime:
{
	"version":	"2.1.0",
	"git branch":	"rc2.1.0",
	"git tag":	"No tag",
	"commit id":	"871ff3c18bb06e3c521275b0e7732b674cddb6dd",
	"commit date":	"2024-03-25 15:29:03 +0800"
}
driver_dependency:
{
	"git branch":	"heads/20240320_develop",
	"git tag":	"20240320_develop",
	"commit id":	"4f591d074070595db19003e5069e78a7ff8942d1",
	"commit date":	"2024-03-20 15:28:45 +0800"
}

报错内容：
{
	"name": "ImportError",
	"message": "libmupti.so.0.2: cannot open shared object file: No such file or directory",
	"stack": "---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[8], line 1
----> 1 import torch
      2 # import torch_musa

File ~/miniconda3/envs/yolov10/lib/python3.9/site-packages/torch/__init__.py:229
    227     if USE_GLOBAL_DEPS:
    228         _load_global_deps()
--> 229     from torch._C import *  # noqa: F403
    231 # Appease the type checker; ordinarily this binding is inserted by the
    232 # torch._C module initialization code in C
    233 if TYPE_CHECKING:

ImportError: libmupti.so.0.2: cannot open shared object file: No such file or directory"
}

**Comment by SChaoZh** [comment]
![截图_2024-08-21_20-58-47](https://github.com/user-attachments/assets/3f803ff9-e79d-4636-8e2d-463e3d6e000d)
![Uploading 截图_2024-08-21_21-00-04.png…]()

**Comment by SChaoZh** [comment]
![Uploading 截图_2024-08-21_21-00-04.png…]()

**Comment by SandroChen** [comment]
解决了吗？我也遇到一样的问题

**Comment by SandroChen** [comment]
安装mccl即可解决。

**Comment by 1823616178** [comment]
解决了吗？我也存在这个问题，我已安装mccl，依然会报错
![image](https://github.com/user-attachments/assets/ae0c0d4c-8c73-4b42-9002-1f465d88d85a)

**Comment by 1823616178** [comment]
![image](https://github.com/user-attachments/assets/2dda2c90-fb9b-4dcb-ad4d-c2bb1978c3e4)

**Comment by 1823616178** [comment]
> 安装mccl即可解决。

不是吧，我在最新的2.1版本的SDK中没有发现有这个mupti的so文件，在本项目的docker文件夹中，发现mupti应该是作为一个独立的包进行安装的，目前官方没有放出来最新的SDK包

**Comment by SandroChen** [comment]
> > 安装mccl即可解决。
> 
> 不是吧，我在最新的2.1版本的SDK中没有发现有这个mupti的so文件，在本项目的docker文件夹中，发现mupti应该是作为一个独立的包进行安装的，目前官方没有放出来最新的SDK包

你是不是在docker上安装的？我在本地装的，安装了mccl就没这个问题了，可以试试看

**Comment by avBuffer** [comment]
(musa) archermind@archermind:~/mgg/MUSA$ mthreads-gmi
Tue Sep 10 18:48:06 2024
---------------------------------------------------------------
    mthreads-gmi:1.9.0           Driver Version:2.7.0
---------------------------------------------------------------
ID   Name           |PCIe                |%GPU  Mem            
     Device Type    |Pcie Lane Width     |Temp  MPC Capable    
+-------------------------------------------------------------+
0    MTT S80        |00000000:01:00.0    |0%    1016MiB(16384MiB)
     Physical       |16x(16x)            |54C   YES            
---------------------------------------------------------------

---------------------------------------------------------------
Processes:
ID   PID       Process name                         GPU Memory
                                                         Usage
+-------------------------------------------------------------+
0    4307      /usr/local/bin/Xorg                      149MiB
0    5034      /usr/bin/gnome-shell                     381MiB
0    5519      /usr/lib/firefox/firefox                 240MiB
0    6173      N/A                                      224MiB
---------------------------------------------------------------
(musa) archermind@archermind:~/mgg/MUSA$ python
Python 3.10.0 (default, Mar  3 2022, 09:58:08) [GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch, torch_musa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/archermind/miniconda3/envs/musa/lib/python3.10/site-packages/torch/__init__.py", line 229, in <module>
    from torch._C import *  # noqa: F403
ImportError: libmupti.so.0.2: cannot open shared object file: No such file or directory
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/archermind/miniconda3/envs/musa/lib/python3.10/site-packages/torch/__init__.py", line 229, in <module>
    from torch._C import *  # noqa: F403
ImportError: libmupti.so.0.2: cannot open shared object file: No such file or directory
>>>

**Comment by SandroChen** [comment]
Sorry there is something wrong with my input method editor, and I can only reply in English. Hope this can help.

Make sure that mccl is installed and install the v1.1.0 version, which can be downloaded from the release page. And run the demo code:

import torch
import torch_musa

a = torch.tensor([1.2, 2.3], dtype=torch.float32, device='musa')
b = torch.tensor([1.2, 2.3], dtype=torch.float32, device='cpu').to('musa')
c = torch.tensor([1.2, 2.3], dtype=torch.float32).musa()

If there is an error occurred with "file cannot be found", copy all the files which's name contains relative chars in "/usr/local/musa/lib" to "/usr/local/lib". 

This works for me. Hope it can solve your problems.

**Comment by hugefrog** [comment]
> > > 安装mccl即可解决。
> > 
> > 
> > 不是吧，我在最新的2.1版本的SDK中没有发现有这个mupti的so文件，在本项目的docker文件夹中，发现mupti应该是作为一个独立的包进行安装的，目前官方没有放出来最新的SDK包
> 
> 你是不是在docker上安装的？我在本地装的，安装了mccl就没这个问题了，可以试试看

麻烦问一下mccl在哪里下载呀？

**Comment by GT-610** [comment]
mccl的下载页面在哪里？我翻遍了官网和仓库都没有找到任何mccl的包的信息。

**Comment by 2926295173** [comment]
> mccl的下载页面在哪里？我翻遍了官网和仓库都没有找到任何mccl的包的信息。

https://docs.mthreads.com/musa-sdk/musa-sdk-doc-online/install_guide

**Comment by 2926295173** [comment]
libmupti.so 是性能分析组件中的导出库。
GIT 地址：https://github.com/MooreThreads/kineto

**Comment by 2926295173** [comment]
编译好的文件在 musa_sdk rc3.1.0中，具体在其中的musa tools里面

**Comment by 1823616178** [comment]
> 编译好的文件在 musa_sdk rc3.1.0中，具体在其中的musa tools里面


> libmupti.so 是性能分析组件中的导出库。 GIT 地址：https://github.com/MooreThreads/kineto

非常感谢，想再问个问题，是这也来编译libmupti的吗

![Image](https://github.com/user-attachments/assets/ecdecb02-06ae-40b0-a1bd-aee0a326fc1b)

**Comment by 2926295173** [comment]
目前不建议自己编译，官方邮件说是Pytorch_musa还没有更新，更新了就会解决这个问题了。

**Comment by 1823616178** [comment]
> 目前不建议自己编译，官方邮件说是Pytorch_musa还没有更新，更新了就会解决这个问题了。

好吧，那就期待新版本
